name: "⭐ Feature"
description: "새로운 기능 추가"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: 📄 구현 기능 / 기획 의도
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
      render: shell
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 기능 구현을 위한 작업 내용을 작성해 주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
      render: shell
    validations:
      required: true
    
  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 참고 자료가 있다면 작성해 주세요.
      render: shell
      value: "- 레퍼런스\n- 에셋\n- etc"

  - type: textarea
    attributes:
      label: 👍 완료 기준
      description: 완료 기준에 대해서 작성해 주세요.
      render: shell
      value: "기획 예: 플레이어가 공격을 하고 상태가 변경\n프로그래밍 예: 공격 로직이 조건에 맞게 작동하고 상태 변경이 됨"

  - type: textarea
    attributes:
      label: 😂 지연(딜레이) 사유
      description: 예상 시간보다 지연됐다면 사유를 작성해 주세요.
      render: shell
      value: "예: 증바람을 너무 많이 해버림"

      
